motors:
  - hrim_actuation_servomotor_000A3500010E:axis2
  - hrim_actuation_servomotor_000A3500010E:axis1
  - hrim_actuation_servomotor_70B3D521A0A6:axis1
  - hrim_actuation_servomotor_70B3D521A0A6:axis2
  - hrim_actuation_servomotor_70B3D521A0A4:axis1
  - hrim_actuation_servomotor_70B3D521A0A4:axis2
