notifications:
  email:
    recipients:
      - lander@erlerobotics.com 
    on_failure: always
matrix:
  include:
    - os: linux
      dist: trusty
  services:
    - docker
  sudo:
    - required
script:
  - docker run -v $(pwd)/travis.sh:/travis.sh acutronicrobotics/mara:dashing-ci bash /travis.sh
